const MAX_CHARS = 500

const DEFAULT_EXPIRATION_SECONDS = 48 * 60 * 60; // 48 hours

const MAX_REFERENCE_TEXT_LENGTH = 200;
const MAX_REFERENCE_SOURCE_LENGTH = 100;

export { DEFAULT_EXPIRATION_SECONDS, MAX_CHARS, MAX_REFERENCE_SOURCE_LENGTH, MAX_REFERENCE_TEXT_LENGTH };
